name: Backend Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.5"

      - name: Install dependencies
        working-directory: marketplace-be
        run: |
          go mod tidy

      - name: Run tests
        working-directory: marketplace-be
        run: |
          set -e
          go test -v ./...
